# kafka.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: messaging

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:latest
          ports:
            - containerPort: 2181

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper.messaging.svc.cluster.local:2181
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
          ports:
            - containerPort: 9092
